### ISSUE TITLE
Feature: runtime assembly registration

### ISSUE THREAD

**Issue by mvit777** [JacopoWolf/StackInjector#134]
**HotLoad and HotUnload of external assemblies**
As per documentation StackInjector is able to load classes from external assemblies but that can only happen if you register the assemblies at compile time. It would be nice if that could be done at runtime

**Use case for this feature**
A windows service would be able to load updated versions of the external assemblies without the need to be restarted.

**Other use case**
A CMS which allows user to load plugins without recompile the core

**More in detail**
The windows service instantiate a ScheduleController every minute. 
The ScheduleController checks a database table (or an xml/json file) to fetch the most recent version of the assemblies and the set of tasks that need to be executed at the current time.
The ScheduleController loads a new thread and a new Domain for each assembly that has tasks to executed at the current time.
The ScheduleController does it through a ProxyObject which gets loaded in the newly create domain.
Every assembly contains a set of classes that perform the tasks.
Every newly created domains get unloaded at the end of tasks or they might be unloaded only if in the next round the ScheduleController finds new versions of the assemblies

**StackInjector should be able to do something like the following...**
`
public class MyProxyObject : MarshalByRefObject
{
    private Type _type;
    private object _object;

    public void InstantiateObject(string AssemblyPath, string typeName, object[] args)
    {
        var oAssembly = Assembly.LoadFrom(AssemblyPath);
        _type = oAssembly.GetType(typeName);
        _object = Activator.CreateInstance(_type, args);
    }

    public void InvokeMethod(string methodName, object[] args)
    {
        var methodinfo = _type.GetMethod(methodName);
        int task_id = System.Convert.ToInt32(args[0]);
        string configs = System.Convert.ToString(args[1]);
        methodinfo.Invoke(_object, new[] { task_id, configs });
    }

    public void SaveVersion()
    {
        var methodInfo = _type.GetMethod("SaveVersion");
        methodInfo.Invoke(_object, null);
    }
}
`
**Final consideration**
What requested above is probably out of scope of StackInjector but indeed would be nice if it could be done

**Comment by JacopoWolf** [comment]
@mvit777  Just as an idea, could something like this be a solution for your problem?

```cs
// the  core wrapper
var defaultsettings ; // default settings
var baseWrapper = Injector.From<MyBase>( defaultsettings )
// some logic here


// the temporary wrapper
{
   var serviceSettings = defaultsettings.Clone()
      .RegisterAssemblies( externalAssemblyIJustLoaded ) 
      .TrackInstantiationDiff( true, callDispose: true );

   // will dispose and clean classes and instances in the externalAssemblyIJustLoaded once out of scope
   using var serviceWrapper = baseWrappper.Clone( serviceSettings ).From<Mybase>()
   serviceWrapper.Entry.DoWork();
}
```
this solution will guarantee that the core instances remain the same (except for the ones marked as alwaysinstantiate, wich should be accounted for somehow) and that variable instances are always updated with the latest versions.

Also, this will ensure that services are wrapped in their own separate wrapper, and except for common instances, modifications will not effect other wrappers.
(you could also intantiate a new wrapper from non-common resources and it will be completely isolated. I mean you can still access the instances and all, but from within it instances cannot interfer with other wrappers)

NOTE: this wouldn't work in versions <=3.1. That's what i have to fix. As of now cloning does not re-register assemblies.

---

As for the feature of `HotLoadAssembly`: I do think it should be integrated in a more comprehensive "runtime editing" context.
It's absolutely a terrific idea, but implementing this would mean to design, implement and test a completely new system to manage and track runtime instances and references and to also "hot swap" them, with all of the problems and complexities and problems of such a system.

For now, i do think implementing the solution described above should do it for you.

**Comment by mvit777** [comment]
I think what I would need now is passing a string with the fullyqualified name of the assembly rather than the type.
Something like this:
`
var wrapper = Injector.From<"TestBot.TestBot">();

But maybe issue #114 will instead fix my problem
`

**Comment by JacopoWolf** [comment]
I believe version `3.1.1` will solve your problem!
```cs
var cloneSettings = mainSettings.Copy()
   .RegisterAfterCloning()
   .TrackInstantiationDiff( callDispose: true )
   .RegisterAssemblies( Assembly.LoadFrom("path\\to\\new\\assembly") );

using var clonedwrapper = mainwrapper.Clone(cloneSettings).ToWrapper<SameEntry>();
```
